### ISSUE TITLE
缺少 图形库

### ISSUE THREAD

**Issue by duyanming** [beginor/docker-jexus-x64#1]
是不是可以加上  libgdiplus

**Comment by beginor** [comment]
我问一下宇内，是放在 jexus 还是镜像中更合适。

**Comment by beginor** [comment]
能否提交一个pr呢？

**Comment by beginor** [comment]
@duyanming 已经问过宇内了， 说 jexus 独立版自带 libgdiplus ， 我也检查了一下， 确实是自带 libgdiplus ， 位于 `/usr/jexus/runtime/lib`  目录下。
