### ISSUE TITLE
在容器内发起HTTPS请求不成功

### ISSUE THREAD

**Issue by catcherwong** [beginor/docker-jexus-x64#2]
用容器运行后，发现HTTPS相关的请求会有问题。

直接进入容器后 用 curl 执行也是报下面这个错。

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

![image](https://user-images.githubusercontent.com/8394988/87215612-c65aa380-c36a-11ea-85fb-03fcac4e7105.png)

**Comment by catcherwong** [comment]
我这边试过下面两种方法可以处理

1.  不remove ca-certificates

https://github.com/beginor/docker-jexus-x64/blob/1e0737308d28b9cc32a9ebcc4b1784e3b8beb081/src/install.sh#L8

这个移除**ca-certificates** 是基于什么考虑吗？

2.  根据报错信息，手动上传最新的 cacert.pem 到容器内， 同时指定环境变量 CURL_CA_BUNDLE。

**Comment by beginor** [comment]
在安装的过程下载 jexus 时需要用到 https ， 所以就安装了 `ca-certificates`。

https://github.com/beginor/docker-jexus-x64/blob/master/src/install.sh#L5

一般镜像构建好之后， 在运行时很少和外部进行 https 通讯了， 为了减少镜像体积， 就删掉了这个。 

你需要用到的话可以再装回去， 或者直接映射宿主机的这个文件。
